variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApplication"

stages:
  - build
  - deploy

before_script:
  - gem install bundler
  - bundle install

build:
  stage: build
  tags:
    - macos
  script:
    - xcodebuild -scheme CounterApplication -configuration Release -sdk iphonesimulator

deploy:
  stage: deploy
  tags:
    - macos
  script:
    - echo "Deploying..."
  only:
    - main
  environment:
    name: production 