variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApplication"

stages:
  - build
  - deploy

before_script:
  - gem install bundler
  - bundle install

build:
  stage: build
  tags:
    - macos
  script:
    - xcodebuild -scheme $APP_NAME -configuration Release -sdk iphonesimulator
  artifacts:
    paths:
      - build/Release-iphonesimulator/

deploy:
  stage: deploy
  tags:
    - macos
  image: google/cloud-sdk:slim
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Release-iphonesimulator/* gs://counter_application/ios-builds/
    - main
  environment:
    name: production 
