variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApp"

stages:
  - build
  - deploy

before_script: []

# Build stage for iOS simulator
build:
  stage: build
  tags:
    - macOS
  script:
    - echo "Building iOS app for simulator..."
    - xcodebuild -scheme $APP_NAME -configuration Release -sdk iphonesimulator -derivedDataPath build
  artifacts:
    paths:
      - build/Build/Products/Release-iphonesimulator/

deploy:
  stage: deploy
  tags:
    - macOS
  image: google/cloud-sdk:slim
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Build/Products/Release-iphonesimulator/* gs://counter_gitcicd_app/ios-builds/
  environment:
    name: production 
