image: 
  name: macos:latest
  entrypoint: [""]

variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApp"
  XCODE_PROJECT: "Number  Counter Application.xcodeproj"
  XCODE_SCHEME: "Number  Counter Application"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - macOS
  script:
    - xcodebuild clean build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphonesimulator
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy_staging:
  stage: deploy
  tags:
    - macOS
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Build/Products/Release-iphonesimulator/* gs://counter_gitcicd_app/ios-builds/staging/
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  tags:
    - macOS
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Build/Products/Release-iphonesimulator/* gs://counter_gitcicd_app/ios-builds/production/
  environment:
    name: production
  only:
    - main
  when: manual 
