image: 
  name: macos:latest
  entrypoint: [""]

variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApp"
  XCODE_PROJECT: "Number  Counter Application.xcodeproj"
  XCODE_SCHEME: "Number  Counter Application"
  APPLE_TEAM_ID: "${APPLE_TEAM_ID}"
  APPLE_DISTRIBUTION_CERTIFICATE: "${APPLE_DISTRIBUTION_CERTIFICATE}"
  APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD: "${APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD}"
  APPLE_PROVISIONING_PROFILE: "${APPLE_PROVISIONING_PROFILE}"
  FASTLANE_USER: "${FASTLANE_USER}"
  FASTLANE_PASSWORD: "${FASTLANE_PASSWORD}"
  MATCH_PASSWORD: "${MATCH_PASSWORD}"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - setup
  - lint
  - test
  - build
  - deploy

before_script:
  - brew install ruby@3.2 swiftlint
  - export PATH="/usr/local/opt/ruby@3.2/bin:$PATH"
  - export LDFLAGS="-L/usr/local/opt/ruby@3.2/lib"
  - export CPPFLAGS="-I/usr/local/opt/ruby@3.2/include"
  - gem uninstall bundler
  - gem install bundler -v 2.4.22
  - bundle config set --local path 'vendor/bundle'
  - bundle install --jobs=4 --retry=3

setup:
  stage: setup
  tags:
    - macOS
  script:
    - export FASTLANE_SKIP_UPDATE_CHECK=true
    - export FASTLANE_HIDE_TIMESTAMP=true
    - export FASTLANE_SKIP_UPDATE_CHECK=true
    - bundle exec fastlane setup_ci
    - xcodebuild -list -project "$XCODE_PROJECT"
    - xcodebuild -scheme "$XCODE_SCHEME" -project "$XCODE_PROJECT" -showBuildSettings
  artifacts:
    paths:
      - vendor/bundle/
    expire_in: 1 week

lint:
  stage: lint
  tags:
    - macOS
  script:
    - swiftlint lint
  allow_failure: true

test:
  stage: test
  tags:
    - macOS
  script:
    - export FASTLANE_SKIP_UPDATE_CHECK=true
    - export FASTLANE_HIDE_TIMESTAMP=true
    - bundle exec fastlane test
  artifacts:
    reports:
      junit: build/reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/coverage.xml
    paths:
      - build/reports/
    expire_in: 1 week

build:
  stage: build
  tags:
    - macOS
  script:
    - export FASTLANE_SKIP_UPDATE_CHECK=true
    - export FASTLANE_HIDE_TIMESTAMP=true
    - bundle exec fastlane build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy_staging:
  stage: deploy
  tags:
    - macOS
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Build/Products/Release-iphonesimulator/* gs://counter_gitcicd_app/ios-builds/staging/
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  tags:
    - macOS
  script:
    - echo "$GCP_SERVICE_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcp-key.json
    - gcloud config set project $PROJECT_ID
    - gsutil cp -r build/Build/Products/Release-iphonesimulator/* gs://counter_gitcicd_app/ios-builds/production/
  environment:
    name: production
  only:
    - main
  when: manual

deploy_testflight:
  stage: deploy
  tags:
    - macOS
  script:
    - export FASTLANE_SKIP_UPDATE_CHECK=true
    - export FASTLANE_HIDE_TIMESTAMP=true
    - bundle exec fastlane beta
  only:
    - main
  when: manual 
