image: xcode:14.3

variables:
  PROJECT_ID: "counterapplication-460304"
  PROJECT_NUMBER: "189419000467"
  APP_NAME: "CounterApp"

stages:
  - build
  - deploy

before_script:
  - gem install bundler
  - bundle install

build:
  stage: build
  script:
    - xcodebuild -scheme CounterApp -configuration Release -sdk iphonesimulator
  artifacts:
    paths:
      - build/Release-iphonesimulator/
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "Installing Google Cloud SDK..."
    - curl https://sdk.cloud.google.com | bash
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud auth activate-service-account --key-file=$GOOGLE_CLOUD_KEY_FILE
    - gcloud config set project $PROJECT_ID
    
    # Enable required APIs
    - gcloud services enable cloudbuild.googleapis.com
    - gcloud services enable cloudresourcemanager.googleapis.com
    - gcloud services enable iam.googleapis.com
    - gcloud services enable run.googleapis.com
    - gcloud services enable logging.googleapis.com
    
    # Add IAM policy binding with specific project number
    - gcloud projects add-iam-policy-binding $PROJECT_ID \
        --member="serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
        --role="roles/cloudbuild.builds.builder"
    
    # Add logging permissions
    - gcloud projects add-iam-policy-binding $PROJECT_ID \
        --member="serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
        --role="roles/logging.logWriter"
    
    # Generate a secret token for webhook
    - export WEBHOOK_SECRET=$(openssl rand -base64 32)
    - echo "Generated Webhook Secret: $WEBHOOK_SECRET"
    
    # Configure webhook with authentication
    - gcloud builds triggers create webhook \
        --name="gitlab-webhook" \
        --description="GitLab webhook trigger" \
        --branch-pattern="main" \
        --build-config="cloudbuild.yaml" \
        --service-account="projects/$PROJECT_ID/serviceAccounts/$PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
        --webhook-config-url="https://cloudbuild.googleapis.com/v1/projects/$PROJECT_ID/triggers/gitlab-webhook:run" \
        --webhook-config-secret="$WEBHOOK_SECRET"
    
    # Store the webhook secret in GitLab CI/CD variables
    - echo "Please add the following as a GitLab CI/CD variable:"
    - echo "WEBHOOK_SECRET: $WEBHOOK_SECRET"
    
    - echo "Deploying to Google Cloud..."
    # Add your deployment commands here
  only:
    - main  # Only deploy from main branch
  environment:
    name: production 