steps:
  # Build the iOS app
  - name: 'xcode:14.3'
    entrypoint: 'xcodebuild'
    args:
      - 'archive'
      - '-scheme'
      - 'CounterApplication'
      - '-configuration'
      - 'Release'
      - '-archivePath'
      - 'build/CounterApplication.xcarchive'
      - '-sdk'
      - 'iphoneos'

  # Export IPA from archive
  - name: 'xcode:14.3'
    entrypoint: 'xcodebuild'
    args:
      - '-exportArchive'
      - '-archivePath'
      - 'build/CounterApplication.xcarchive'
      - '-exportPath'
      - 'build/export'
      - '-exportOptionsPlist'
      - 'exportOptions.plist'

  # Upload IPA to GCP bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'build/export/CounterApplication.ipa'
      - 'gs://${_BUCKET_NAME}/ios-builds/CounterApplication-${BUILD_ID}.ipa'

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _BUCKET_NAME: 'counter_gitcicd_app'  # Replace with your actual bucket name

# Deploy step (placeholder for your deployment needs)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'counter-application'
    - '--image'
    - 'gcr.io/$PROJECT_ID/counter-application'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated' 