steps:
  # Build the iOS app
  - name: 'xcode:14.3'
    entrypoint: 'xcodebuild'
    args:
      - '-scheme'
      - 'CounterApplication'
      - '-configuration'
      - 'Release'
      - '-sdk'
      - 'iphonesimulator'

  # Deploy step (placeholder for your deployment needs)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'counter-application'
      - '--image'
      - 'gcr.io/$PROJECT_ID/counter-application'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET 