default_platform(:ios)

platform :ios do
  desc "Setup CI environment"
  lane :setup_ci do
    setup_ci
  end

  desc "Build the app"
  lane :build do
    build_ios_app(
      project: "Number  Counter Application.xcodeproj",
      scheme: "Number  Counter Application",
      clean: true,
      output_directory: "build"
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      project: "Number  Counter Application.xcodeproj",
      scheme: "Number  Counter Application",
      device: "iPhone 16 Pro",
      clean: true
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    build_ios_app(
      project: "Number  Counter Application.xcodeproj",
      scheme: "Number  Counter Application",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end 